version: '3.3'
services:
  app:
    image: ir-api:1.0
    ports:
      - 8085:8080
    networks:
      - irs-network

  db:
    image: mongo
    ports:
      - 27017-27019:27017-27019
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_DB}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASS}
    volumes:
      - .docker/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - .docker/mongo/volume:/data/db
    networks:
      - irs-network

networks:
  irs-network:
    driver: bridge
