openapi: '3.0.0'
info:
  description: 'Backend to manage Island Reservations'
  version: 1.0.0
  title: Island Reservation API

paths:
  /reservations:
    post:
      tags:
        - Reservations
      summary: Create a new reservation
      operationId: addReservation
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Reservation'
      responses:
        '200':
          description: 'Successfully created reservation.'
          content:
            application/json:
              schema:
                type: string

  /reservations/{resevation_id}:
    get:
      tags:
        - Reservations
      summary: gets an existing reservation
      operationId: getReservation
      parameters:
        - in: path
          name: resevation_id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: 'Successfully retrieved reservation'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Reservation'

  /reservations/{resevation_id}/{transaction}:
    put:
      tags:
        - Reservations
      summary: Modifies an existing reservation
      operationId: updateReservation
      parameters:
        - in: path
          name: resevation_id
          required: true
          schema:
            type: string
        - in: path
          name: transaction
          required: true
          schema:
            type: string
            enum: [ MODIFY, CANCEL ]
      requestBody:
        required: false
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Reservation'
      responses:
        '200':
          description: 'Successfully updated reservation.'

  /campsite/calendar/dates:
    get:
      tags:
        - Calendar
      summary: get campsite availability
      parameters:
        - in: query
          name: status
          required: true
          schema:
            type: string
            enum: [ AVAILABLE, NOT_AVAILABLE ]
        - in: query
          name: range
          required: true
          schema:
            type: string
            enum: [ WEEK, MONTH ]
            default: MONTH

      responses:
        '200':
          description: 'Successfully retrieved reservation'
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
                  format: date

components:
  schemas:
    Reservation:
      required: [
          "client",
          "startDate",
          "endDate"
      ]
      type: object
      properties:
        client:
          $ref: '#/components/schemas/Client'
        startDate:
          type: string
          format: date
        endDate:
          type: string
          format: date

    Client:
      required: [
          "email"
      ]
      type: object
      properties:
        email:
          type: string
          format: email
          example: user@example.com
        firstName:
          type: string
        lastName:
          type: string

    Error:
      required: [
          "code"
      ]
      type: object
      properties:
        code:
          type: string
          enum: [ IR00,IR01,IR02,IR03 ]
        message:
          type: string